<!DOCTYPE html>
<html lang="en_US">
<head>
    <meta charset="UTF-8"/>
    <title>Authors</title>
    <link href="../../lib/tabulator/css/tabulator_simple.css" rel="stylesheet">
    <link href="../../author/article.css" rel="stylesheet">
    <link href="../../common/sidebar.css" rel="stylesheet">
    <script type="text/javascript" src="../../static/lib/tabulator/js/tabulator.js" defer></script>
    <script type="text/javascript" src="../../static/author/index.js" defer></script>
</head>

<body>
<div id="page-container">
    <#-- pull in the sidebar -->
    <#include "../common/sidebar.ftlh"/>
    <main id="main-content">
        <h1>Manage Authors</h1>
        <button id="add-article-button">Add New Author</button>
    </main>
</div>

</body>
</html>
